---
# Source: bucstop/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
apiVersion: v1
kind: Service
metadata:
  name: gamemicropong
spec:
  type: ClusterIP
  selector:
    app: gamemicropong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
apiVersion: v1
kind: Service
metadata:
  name: gamemicrosnake
spec:
  type: ClusterIP
  selector:
    app: gamemicrosnake
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
apiVersion: v1
kind: Service
metadata:
  name: gamemicrotetris
spec:
  type: ClusterIP
  selector:
    app: gamemicrotetris
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
# Source: bucstop/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "sirethan/bucstop:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamemicropong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamemicropong
  template:
    metadata:
      labels:
        app: gamemicropong
    spec:
      containers:
        - name: gamemicropong
          image: "sirethan/gamemicropong:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamemicrosnake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamemicrosnake
  template:
    metadata:
      labels:
        app: gamemicrosnake
    spec:
      containers:
        - name: gamemicrosnake
          image: "sirethan/gamemicrosnake:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamemicrotetris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamemicrotetris
  template:
    metadata:
      labels:
        app: gamemicrotetris
    spec:
      containers:
        - name: gamemicrotetris
          image: "sirethan/gamemicrotetris:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: "tomphlpps/bucstop-gateway:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:80"
            - name: PONG_SERVICE_URL
              value: "http://gamemicropong"
            - name: SNAKE_SERVICE_URL
              value: "http://gamemicrosnake"
            - name: TETRIS_SERVICE_URL
              value: "http://gamemicrotetris"
