{{- range $name, $config := .Values }}
{{- if $config.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
          imagePullPolicy: "{{ $config.image.pullPolicy }}"
          ports:
            - containerPort: {{ $config.service.port }}
          env:
            {{- range $key, $value := $config.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
{{- end }}
{{- end }}

